<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/14.0.1">
  <PropertyGroup>
      <Author>darkarchon, wozaiha</Author>
      <Name>Mare Synchronos</Name>
      <InternalName>mareSynchronos</InternalName>
      <AssemblyVersion>1.14.0.2</AssemblyVersion>
      <Description>/mare</Description>
      <Punchline>Be Quiet~</Punchline>
      <RepoUrl>https://github.com/ottercorp/Mare-client</RepoUrl>
      <IconUrl>https://raw.githubusercontent.com/ottercorp/Mare-client/CN/MareSynchronos/images/icon.png</IconUrl>
      
  </PropertyGroup>

  <PropertyGroup>
    <Platforms>x64</Platforms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockfileAssemblies>true</CopyLocalLockfileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PlayerData\Export\**" />
    <EmbeddedResource Remove="PlayerData\Export\**" />
    <None Remove="PlayerData\Export\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DeviceId" Version="6.9.0" />
    <PackageReference Include="DeviceId.Linux" Version="6.9.0" />
    <PackageReference Include="DeviceId.Mac" Version="6.9.0" />
    <PackageReference Include="DeviceId.Windows" Version="6.9.0" />
    <PackageReference Include="Downloader" Version="4.0.3" />
    <PackageReference Include="K4os.Compression.LZ4.Legacy" Version="1.3.8" />
    <PackageReference Include="Meziantou.Analyzer" Version="2.0.260">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Glamourer.Api" Version="2.8.0" />
    <PackageReference Include="NReco.Logging.File" Version="1.3.1" />
    <PackageReference Include="Penumbra.Api" Version="5.13.1" />
    <PackageReference Include="Penumbra.String" Version="1.0.7" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.16.1.129956">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
    <PackageReference Include="System.Management" Version="10.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <SourceRevisionId>build$([System.DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss:fffZ"))</SourceRevisionId>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MareAPI\MareSynchronosAPI\MareSynchronos.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CheapLoc">
      <HintPath>$(DalamudLibPath)CheapLoc.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="images\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Localization\de.json" />
    <EmbeddedResource Include="Localization\zh.json" />
    <EmbeddedResource Include="Localization\fr.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

    <Target Name="PostBuildCopyFiles" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
    <Copy
            SourceFiles="$(TargetDir)MareSynchronos\MareSynchronos.json"
            DestinationFolder="$(ProjectDir)..\repo\CN\"
            OverwriteReadOnlyFiles="true" />
        
    <Copy
            SourceFiles="$(TargetDir)MareSynchronos\latest.zip"
            DestinationFiles="$(ProjectDir)..\repo\CN\$(AssemblyVersion).zip"
            OverwriteReadOnlyFiles="true" />
    </Target>

</Project>